[package]
name = "lrvm_tools"
version = "0.2.1"
authors = ["Clément Nerma <clement.nerma@gmail.com>"]
edition = "2018"

[dependencies]
lrvm = { path = "../lrvm" }
customasm = { git = "https://github.com/hlorenzi/customasm.git", tag = "v0.11.14" }
