[package]
authors = ["Clément Nerma <clement.nerma@gmail.com>"]
edition = "2021"
name = "hw_detect"
version = "0.1.0"

[dependencies]
rand = "0.8.5"
lrvm = { path = "../../lrvm" }
lrvm_aux = { path = "../../lrvm_aux" }
lrvm_tools = { path = "../../lrvm_tools" }
