[package]
authors = ["Clément Nerma <clement.nerma@gmail.com>"]
edition = "2018"
name = "hw_detect"
version = "0.1.0"

[dependencies]
rand = "0.7.3"
mrvm = { path = "../../mrvm" }
mrvm_aux = { path = "../../mrvm_aux" }
mrvm_tools = { path = "../../mrvm_tools" }
