[workspace]
members = [
    "mrvm",
    "mrvm_aux",
    "mrvm_tools",
    "examples/minimal",
    "examples/hello_world",
    "examples/elapsed_time",
    "examples/hw_detect",
    "examples/async_hw"
]
