[package]
name = "benchmark"
version = "0.1.0"
authors = ["Clément Nerma <clement.nerma@gmail.com>"]
edition = "2021"

[dependencies]
lrvm_aux = { path = "../../lrvm_aux" }
lrvm_tools = { path = "../../lrvm_tools" }
