[package]
name = "brainfuck"
version = "0.1.0"
authors = ["Clément Nerma <clement.nerma@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.8.5"
crossterm = "0.23.2"
lrvm = { path = "../../lrvm" }
lrvm_aux = { path = "../../lrvm_aux" }
lrvm_tools = { path = "../../lrvm_tools" }
