[package]
name = "brainfuck"
version = "0.1.0"
authors = ["Clément Nerma <clement.nerma@gmail.com>"]
edition = "2021"

[dependencies]
rand = "0.9.0"
crossterm = "0.28.1"
lrvm = { path = "../../lrvm" }
lrvm_aux = { path = "../../lrvm_aux" }
lrvm_tools = { path = "../../lrvm_tools" }
