[package]
name = "brainfuck"
version = "0.1.0"
authors = ["Clément Nerma <clement.nerma@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.3"
crossterm = "0.18.2"
mrvm = { path = "../../mrvm" }
mrvm_aux = { path = "../../mrvm_aux" }
mrvm_tools = { path = "../../mrvm_tools" }
