[package]
name = "mrvm_tools"
version = "0.1.0"
authors = ["Clément Nerma <clement.nerma@gmail.com>"]
edition = "2018"

[dependencies]
mrvm = { path = "../mrvm" }
customasm = { git = "https://github.com/hlorenzi/customasm.git" }
